# Generated by Django 5.0.11 on 2025-01-18 21:25

import ckeditor.fields
import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titel')),
                ('tag', models.CharField(choices=[('JavaScript', 'Javascript'), ('HTML', 'HTML'), ('Python', 'Python'), ('Unreal Engine 5', 'UE5'), ('Vue.js', 'Vue.js')], default='', verbose_name='Wähle ein Tag aus')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Beschreibung')),
                ('image_left_alt', models.CharField(max_length=200, verbose_name='links Image Alt Text')),
                ('image_left_title', models.CharField(max_length=200, verbose_name='links Image Titel')),
                ('image_right_alt', models.CharField(max_length=200, verbose_name='Image rechts Alt Text')),
                ('image_right_title', models.CharField(max_length=200, verbose_name='Image rechts Titel')),
                ('image_left', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codeproject_left_images', to=settings.FILER_IMAGE_MODEL, verbose_name='linkes Bild')),
                ('image_right', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codeproject_right_images', to=settings.FILER_IMAGE_MODEL, verbose_name='rechtes Bild')),
            ],
        ),
        migrations.CreateModel(
            name='CodingSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Code Language')),
                ('icon', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Icon')),
            ],
        ),
    ]
